#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const args = process.argv.slice(2);

// Map common layout weights, abbreviations, and project initials to CSS properties and short naming fragments
function getFontDetails(fileName) {
  const lower = fileName.toLowerCase();
  let weight = '400';
  let style = 'normal';
  
  let weightAbbr = 'Rg';
  let styleAbbr = '';

  if (lower.includes('italic')) {
    style = 'italic';
    styleAbbr = '_Ital';
  }

  // Map absolute font weights securely
  if (lower.includes('extrabold')) {
    weight = '800';
    weightAbbr = 'Ex_Bd';
  } else if (lower.includes('semibold')) {
    weight = '600';
    weightAbbr = 'Semi_Bd';
  } else if (lower.includes('bold')) {
    weight = '700';
    weightAbbr = 'Bd';
  } else if (lower.includes('heavy') || lower.includes('_he')) {
    weight = '900';
    weightAbbr = 'He';
  } else if (lower.includes('medium')) {
    weight = '500';
    weightAbbr = 'Md';
  } else if (lower.includes('extralight')) {
    weight = '200';
    weightAbbr = 'Ex_Lt';
  } else if (lower.includes('light') || lower.includes('_lt')) {
    weight = '300';
    weightAbbr = 'Lt';
  } else if (lower.includes('thin')) {
    weight = '100';
    weightAbbr = 'Th';
  } else if (lower.includes('_rg') || lower.includes('regular')) {
    weight = '400';
    weightAbbr = 'Rg';
  }

  if (style === 'italic' && weightAbbr === 'Rg' && !lower.includes('regular') && !lower.includes('_rg')) {
    weightAbbr = ''; 
    styleAbbr = 'Ital';
  }

  // FIX: Split on dashes (-), underscores (_), OR spaces (\s) to isolate the first word cleanly
  const parts = fileName.split(/[-_\s]+/);
  const firstPart = parts[0]; 

  let fileInitialPrefix = firstPart;
  let cssFontFamily = firstPart;
  
  // Extract capital letters to make an acronym only if the name has camelCase/PascalCase words (e.g. PlusJakartaSans)
  const upperCaseMatches = firstPart.match(/[A-Z]/g);
  if (upperCaseMatches && upperCaseMatches.length > 1) {
    fileInitialPrefix = upperCaseMatches.join(''); // e.g., 'PJS'
    
    // Add clean spaces between capital letters for the readable font-family name
    cssFontFamily = firstPart.replace(/([A-Z])/g, ' $1').trim(); // e.g., 'Plus Jakarta Sans'
  } else {
    // If the name is lowercase or single word (e.g. effra), capitalize the first letter nicely
    fileInitialPrefix = firstPart.charAt(0).toUpperCase() + firstPart.slice(1);
    cssFontFamily = fileInitialPrefix;
  }

  let cleanSuffix = weightAbbr + styleAbbr;
  if (weightAbbr && styleAbbr) {
    cleanSuffix = `${weightAbbr}${styleAbbr}`;
  }
  
  const shortFileName = cleanSuffix ? `${fileInitialPrefix}_${cleanSuffix}` : fileInitialPrefix;

  return { cssFontFamily, fileInitialPrefix, weight, style, shortFileName };
}

if (args[0] === 'from' && args[2] === 'to' && args[3] === 'woff2') {
  const srcExt = args[1].toLowerCase();
  const currentDir = process.cwd();
  
  const files = fs.readdirSync(currentDir);
  const targetFiles = files.filter(file => path.extname(file).toLowerCase() === `.${srcExt}`);

  if (targetFiles.length === 0) {
    console.error(`Error: No *.${srcExt} files found in this directory.`);
    process.exit(1);
  }

  console.log(`Found ${targetFiles.length} files. Starting conversion...`);
  
  // Object to store accumulated CSS rules grouped by the short file initial prefix
  const cssMap = {};

  targetFiles.forEach(file => {
    const baseName = path.basename(file, path.extname(file));
    const { cssFontFamily, fileInitialPrefix, weight, style, shortFileName } = getFontDetails(baseName);
    
    // Outputs super-short compressed file configurations
    const outputFile = `${shortFileName}.woff2`;
    
    console.log(`Converting & Renaming: ${file} -> ${outputFile}`);
    
    try {
      // Execute the conversion stream to the newly compressed short filename
      execSync(`ttf2woff2 < "${file}" > "${outputFile}"`, { stdio: 'ignore' });
      
      // Initialize family array inside our map if it doesn't exist yet (grouped by PJS, Effra, etc.)
      if (!cssMap[fileInitialPrefix]) {
        cssMap[fileInitialPrefix] = `/* Generated by fonts-converter for ${cssFontFamily} */\n\n`;
      }

      // Construct font-face rule using the clean readable font-family name and short output path
      cssMap[fileInitialPrefix] += `@font-face {\n`;
      cssMap[fileInitialPrefix] += `  font-family: '${cssFontFamily}';\n`;
      cssMap[fileInitialPrefix] += `  src: url('./${outputFile}') format('woff2');\n`;
      cssMap[fileInitialPrefix] += `  font-weight: ${weight};\n`;
      cssMap[fileInitialPrefix] += `  font-style: ${style};\n`;
      cssMap[fileInitialPrefix] += `  font-display: swap;\n`;
      cssMap[fileInitialPrefix] += `}\n\n`;

    } catch (err) {
      console.error(`Failed to convert ${file}:`, err.message);
    }
  });

  // Iterate through our map and write individual short CSS files (PJS.css, Effra.css)
  Object.keys(cssMap).forEach(prefix => {
    const cssFileName = `${prefix}.css`;
    fs.writeFileSync(path.join(currentDir, cssFileName), cssMap[prefix].trim() + '\n');
    console.log(`Generated stylesheet: ${cssFileName}`);
  });

  console.log('Success: Conversion complete!');
} else {
  console.log('\nInvalid syntax. Use one of these formats:');
  console.log('  fonts-converter from ttf to woff2');
  console.log('  fonts-converter from otf to woff2\n');
}
